apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: Logstash
  name: ocp-logstash
spec:
  dockerImageRepository: "docker.elastic.co/logstash/logstash"
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: docker.elastic.co/logstash/logstash:5.6.4
    importPolicy: {}
    name: "5.6.4"
  - annotations: null
    from:
      kind: ImageStreamTag
      name: "5.6.4"
    importPolicy: {}
    name: "5.6"
  - annotations: null
    from:
      kind: DockerImage
      name: docker.elastic.co/logstash/logstash:latest
    importPolicy: {}
    name: latest

