apiVersion: v1
kind: Template
labels:
        template: ocp-logstash-ephemeral-template
message: |-
  The following service(s) have been created in your project: ${LOGSTASH_SERVICE_NAME}.

metadata:
  annotations:
    description: |-
      Logstash service, without persistent storage.

      WARNING: Any data stored will be lost upon pod destruction. Only use this template for testing
    iconClass: icon-logstash
    openshift.io/display-name: OCP-Logstash (Ephemeral)
    tags: logstash
    template.openshift.io/provider-display-name: SDP Team
    template.openshift.io/support-url: https://svcmgr.cdc.gov/
  creationTimestamp: null
  name: ocp-logstash-ephemeral
objects:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: ${LOGSTASH_SERVICE_NAME}
  spec:
    ports:
    - name: logstash
      protocol: TCP
      port: 9600 
      targetPort: 9600
    selector:
      name: ${LOGSTASH_SERVICE_NAME}
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: ${LOGSTASH_SERVICE_NAME}
  spec:
    replicas: 1
    selector:
      name: ${LOGSTASH_SERVICE_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: ${LOGSTASH_SERVICE_NAME}
      spec:
        containers:
        - capabilities: {}
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms${MEMORY_LIMIT} -Xmx${MEMORY_LIMIT}"
          - name: ELASTICSEARCH_URL
            value: "${ELASTICSEARCH_URL}"
          image: ' '
          imagePullPolicy: IfNotPresent
          readinessProbe:
            initialDelaySeconds: 3
            tcpSocket:
              port: 9600
            timeoutSeconds: 1
          livenessProbe:
            initialDelaySeconds: 30
            tcpSocket:
              port: 9600
            timeoutSeconds: 1
          name: logstash
          ports:
          - containerPort: 9600
            protocol: TCP
          resources:
            limits:
              memory: ${MEMORY_LIMIT}
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /usr/share/logstash/data
            name: ${LOGSTASH_SERVICE_NAME}-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        volumes:
        - emptyDir:
            medium: ""
          name: ${LOGSTASH_SERVICE_NAME}-data
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - logstash
        from:
          kind: ImageStreamTag
          name: ${LOGSTASH_IMAGE}:${LOGSTASH_VERSION}
          namespace: ${NAMESPACE}
        lastTriggeredImage: ""
      type: ImageChange
    - type: ConfigChange
  status: {}
parameters:
- description: URL for the Elasticsearch service.
  displayName: Elasticsearch URL
  name: ELASTICSEARCH_URL
  required: true
  value: http://elasticsearch:9200
- description: Maximum amount of memory the container can use.
  displayName: Memory Limit
  name: MEMORY_LIMIT
  required: true
  value: 1Gi
- description: The OpenShift Namespace where the ImageStream resides.
  displayName: Namespace
  name: NAMESPACE
  value: openshift
- description: The name of the OpenShift Service exposed for the database.
  displayName: Logstash Service Name
  name: LOGSTASH_SERVICE_NAME
  required: true
  value: logstash
- description: The name of the Logstash imagestream to be used.
  displayName: Logstash Image Name
  name: LOGSTASH_IMAGE
  value: ocp-logstash
- description: Version of Logstash image to be used (5.6.4).
  displayName: Version of Logstash Image
  name: LOGSTASH_VERSION
  required: true
  value: "5.6"

